swagger: '2.0'
info:
  description: This is a simple API
  version: 1.0.0
  title: Simple Inventory API
  # put the contact info for your development or API team
  contact:
    email: you@your-company.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers

paths:
  /livro/:
    get:
      tags:
      - livro
      summary: searches livro
      operationId: searchLivro
      description: |
        Retorna todos os itens da livraria
      produces:
      - application/json
      - application/xml
      parameters: []
      responses:
        200:
          description: Sucesso
          schema:
            type: object
            items:
              $ref: '#/definitions/livro'
        400:
          description: bad input parameter
    post:
      tags:
      - livro
      summary: add an livro
      operationId: createLivro
      consumes:
      - application/json
      - application/xml
      produces:
      - application/json
      - application/xml
      parameters:
      - in: body
        name: body
        description: Created an livro
        required: true
        schema:
          $ref: '#/definitions/livro'
      responses:
        201:
          description: item created
        405:
          description: invalid input
  /livro/{livroId}:
    get:
      tags:
      - livro
      summary: find livro by ID
      operationId: getLivroById
      description: |
        Retorna um livro específico
      produces:
      - application/json
      - application/xml
      parameters:
      - in: path
        name: livroId
        description: ID of livro to return
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: Livro encontrado
          schema:
              $ref: '#/definitions/livro'
        400:
          description: Invalid ID supplied
        404:
          description: Livro not found
    delete:
      tags:
      - livro
      summary: delete livro by ID
      operationId: deleteLivroById
      description: |
        Deleta o livro informado
      produces:
      - application/json
      - application/xml
      parameters:
      - name: livroId
        in: path
        description: ID of delete 
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: Deletado com sucesso
        400:
          description: Invalid ID supplied
        404:
          description: Livro not found
definitions:
  livro:
    type: object
    required:
    - isbn
    - titulo
    - autor
    properties:
      isbn:
        type: integer
        format: int64
      titulo:
        type: string
        example: The Origin
      autor:
        type: string
        example: Lucas de Paula
    xml:
      name: livro
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /lucasdepaula19/LivrariaLucas/1.0.0
schemes:
 - https