/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SimpleInventoryApi);
  }
}(this, function(expect, SimpleInventoryApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SimpleInventoryApi.Livro();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Livro', function() {
    it('should create an instance of Livro', function() {
      // uncomment below and update the code to test Livro
      //var instance = new SimpleInventoryApi.Livro();
      //expect(instance).to.be.a(SimpleInventoryApi.Livro);
    });

    it('should have the property isbn (base name: "isbn")', function() {
      // uncomment below and update the code to test the property isbn
      //var instance = new SimpleInventoryApi.Livro();
      //expect(instance).to.be();
    });

    it('should have the property titulo (base name: "titulo")', function() {
      // uncomment below and update the code to test the property titulo
      //var instance = new SimpleInventoryApi.Livro();
      //expect(instance).to.be();
    });

    it('should have the property autor (base name: "autor")', function() {
      // uncomment below and update the code to test the property autor
      //var instance = new SimpleInventoryApi.Livro();
      //expect(instance).to.be();
    });

  });

}));
